### ISSUE TITLE
What should happen on first run?

### ISSUE THREAD

**Issue by telemachus** [DhavalKapil/luavm#4]
Hi,

As things stand, if the user downloads and runs anything, including `./luavm help`, `luavm` tries to install all its default working directories (`~/.luavm` etc.).

I'm not sure I think that this is the best procedure. I think it would be better to install those *only* when a user runs a command that requires them.

Beyond that, the installation commands have a problem. This is what the user sees when running `./luavm help`

    $ ./luavm help
    usage: mkdir [-pv] [-m mode] directory ...
    Unable to execute following command:
    mkdir 
    Exiting

**Comment by DhavalKapil** [comment]
Ideally, the user should have installed `luavm` as given in the README. The directories that are created in `./luavm` are just for making sure the user didn't delete any of these. I don't think it matters much to include them in every run.

And yes that is a bug that happens when the user didn't install it and directly ran `./luavm`. I'll fix it.

Thanks!
